<?php

namespace Modules\Catalog;

use Dnsoft\Core\Support\BaseModuleServiceProvider;
use Illuminate\Support\ServiceProvider;

class CustomerServiceProvider extends BaseModuleServiceProvider
{
    public function getModuleNamespace()
    {
        return 'catalog';
    }

    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

}
