<?php

namespace Modules\Customer;

use Dnsoft\Core\Support\BaseModuleServiceProvider;
use Illuminate\Support\ServiceProvider;
use Modules\Customer\Models\Customer;
use Modules\Customer\Models\CustomerAddress;
use Modules\Customer\Models\CustomerGroup;
use Modules\Customer\Repositories\CustomerGroupRepositoryInterface;
use Modules\Customer\Repositories\CustomerRepositoryInterface;
use Modules\Customer\Repositories\Eloquents\CustomerAddressRepository;
use Modules\Customer\Repositories\Eloquents\CustomerGroupRepository;
use Modules\Customer\Repositories\Eloquents\CustomerRepository;
use Modules\Customer\Repositories\CustomerAddressRepositoryInterface;

class CustomerServiceProvider extends BaseModuleServiceProvider
{
    public function getModuleNamespace()
    {
        return 'customer';
    }

    public function boot()
    {
        parent::boot();

        $this->app->singleton(CustomerRepositoryInterface::class, function () {
            return new CustomerRepository(new Customer());
        });

        $this->app->singleton(CustomerAddressRepositoryInterface::class, function () {
            return new CustomerAddressRepository(new CustomerAddress());
        });

        $this->app->singleton(CustomerGroupRepositoryInterface::class, function () {
            return new CustomerGroupRepository(new CustomerGroup());
        });
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

}
